#!/usr/bin/env bash

set -e

content=$(cat $1)

cd $(dirname $0)
main_swift="Sources/PackageDescription/main.swift"

echo "$content" > $main_swift
echo "" >> $main_swift
echo 'import Foundation' >> $main_swift
echo 'print(String(data: try JSONEncoder().encode(package), encoding: .utf8) ?? "")' >> $main_swift
swift run 2>/dev/null
